### ISSUE TITLE
UI Bug Report

### ISSUE THREAD

**Issue by chonglee123456** [gravitl/netmaker-ui-2#840]
Describe what happened...

 Error log: 
`NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
{
    "componentStack": "\n    at span\n    at button\n    at rfe (https://dashboard.netbird.cc/assets/index-8bf3ce36.js:176:16319)\n    at Wfe (https://dashboard.netbird.cc/assets/index-8bf3ce36.js:176:33339)\n    at div\n    at Yl (https://dashboard.netbird.cc/assets/index-8bf3ce36.js:40:27486)\n    at div\n    at https://dashboard.netbird.cc/assets/index-8bf3ce36.js:357:8913\n    at div\n    at A4 (https://dashboard.netbird.cc/assets/index-8bf3ce36.js:63:131)\n    at AU (https://dashboard.netbird.cc/assets/index-8bf3ce36.js:195:44053)\n    at div\n    at div\n    at https://dashboard.netbird.cc/assets/index-8bf3ce36.js:184:1646\n    at div\n    at https://dashboard.netbird.cc/assets/index-8bf3ce36.js:184:1809\n    at n (https://dashboard.netbird.cc/assets/index-8bf3ce36.js:95:7631)\n    at https://dashboard.netbird.cc/assets/index-8bf3ce36.js:95:12462\n    at https://dashboard.netbird.cc/assets/index-8bf3ce36.js:184:3552\n    at div\n    at div\n    at rhe (https://dashboard.netbird.cc/assets/index-8bf3ce36.js:184:4597)\n    at https://dashboard.netbird.cc/assets/index-8bf3ce36.js:184:278\n    at K4 (https://dashboard.netbird.cc/assets/index-8bf3ce36.js:184:6614)\n    at my (https://dashboard.netbird.cc/assets/index-8bf3ce36.js:195:43088)\n    at Gh (https://dashboard.netbird.cc/assets/index-8bf3ce36.js:176:18797)\n    at Yl (https://dashboard.netbird.cc/assets/index-8bf3ce36.js:40:27486)\n    at iE (https://dashboard.netbird.cc/assets/index-8bf3ce36.js:556:5384)\n    at main\n    at https://dashboard.netbird.cc/assets/index-8bf3ce36.js:394:46710\n    at KVe (https://dashboard.netbird.cc/assets/index-8bf3ce36.js:936:75962)\n    at cs (https://dashboard.netbird.cc/assets/index-8bf3ce36.js:936:93183)\n    at P3e (https://dashboard.netbird.cc/assets/index-8bf3ce36.js:512:4029)\n    at U3e (https://dashboard.netbird.cc/assets/index-8bf3ce36.js:512:7295)\n    at main\n    at https://dashboard.netbird.cc/assets/index-8bf3ce36.js:394:46710\n    at div\n    at Yl (https://dashboard.netbird.cc/assets/index-8bf3ce36.js:40:27486)\n    at div\n    at Yl (https://dashboard.netbird.cc/assets/index-8bf3ce36.js:40:27486)\n    at Yl (https://dashboard.netbird.cc/assets/index-8bf3ce36.js:40:27486)\n    at rLe (https://dashboard.netbird.cc/assets/index-8bf3ce36.js:543:24907)\n    at P3e (https://dashboard.netbird.cc/assets/index-8bf3ce36.js:512:4029)\n    at Yl (https://dashboard.netbird.cc/assets/index-8bf3ce36.js:40:27486)\n    at lPe (https://dashboard.netbird.cc/assets/index-8bf3ce36.js:521:4801)\n    at W3e (https://dashboard.netbird.cc/assets/index-8bf3ce36.js:512:7333)\n    at aPe (https://dashboard.netbird.cc/assets/index-8bf3ce36.js:521:2042)\n    at lue (https://dashboard.netbird.cc/assets/index-8bf3ce36.js:95:16355)\n    at gue (https://dashboard.netbird.cc/assets/index-8bf3ce36.js:95:17413)\n    at Yl (https://dashboard.netbird.cc/assets/index-8bf3ce36.js:40:27486)\n    at div\n    at e9 (https://dashboard.netbird.cc/assets/index-8bf3ce36.js:941:146448)\n    at i7 (https://dashboard.netbird.cc/assets/index-8bf3ce36.js:936:238319)"
}`

**Comment by yabinma** [comment]
@chonglee123456 , can you please provide the re-reproduce steps?  A screenshot will be helpful.
